import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/views/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#FF9580",
          "primary-content": "#2B1F1A",
          secondary: "#FFB6A3",
          "secondary-content": "#2B1F1A",
          accent: "#66D9D9",
          "accent-content": "#ffffff",
          neutral: "#6b7280",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#FFE5DC",
          "base-300": "#F5E5DD",
          "base-content": "#2B1F1A",
          info: "#3b82f6",
          "info-content": "#ffffff",
          success: "#10b981",
          "success-content": "#ffffff",
          warning: "#f59e0b",
          "warning-content": "#ffffff",
          error: "#ef4444",
          "error-content": "#ffffff",
        },
      },
      {
        dark: {
          primary: "#FF9580",
          "primary-content": "#ffffff",
          secondary: "#FFB6A3",
          "secondary-content": "#ffffff",
          accent: "#66D9D9",
          "accent-content": "#000000",
          neutral: "#2a2a2a",
          "neutral-content": "#d1d5db",
          "base-100": "#2B1F1A",
          "base-200": "#3D2F27",
          "base-300": "#4A3A32",
          "base-content": "#ffffff",
          info: "#3b82f6",
          "info-content": "#ffffff",
          success: "#10b981",
          "success-content": "#ffffff",
          warning: "#f59e0b",
          "warning-content": "#000000",
          error: "#ef4444",
          "error-content": "#ffffff",
        },
      },
    ],
  },
  plugins: [require("daisyui")],
};
export default config;
